# dependabot.yml config file

version: 2
updates:
  # Enable version updates for javascript (npm, yarn)
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    assignees:
      - "szymonsterczewski"
