import { InputEmail, InputNumber, InputPhoneNumber, InputText, InputSwitch, InputCheckbox, InputCheckboxGroup, InputRadio, InputCopy, InputTextarea, InputUrl, InputCurrency, DatePicker, DatePrevNextPicker, DateRangePicker, InputSelect, FormButton, Download, StepBar, Alert, Modal, Chart, ImageCropper, ConfirmDialog, Copy, Tooltip, Tabs, Pagination, Table, Sort, DropDownActions } from './components';
// import { useConfirmDialog, provideConfirmDialog } from './composables';

export default {
    InputEmail,
    InputNumber,
    InputPhoneNumber,
    InputText,
    InputSwitch,
    InputCheckbox,
    InputCheckboxGroup,
    InputRadio,
    InputCopy,
    InputTextarea,
    InputUrl,
    InputCurrency,
    DatePicker,
    DatePrevNextPicker,
    DateRangePicker,
    InputSelect,
    FormButton,
    Download,
    StepBar,
    Alert,
    Modal,
    Chart,
    ImageCropper,
    ConfirmDialog,
    Copy,
    Tooltip,
    Tabs,
    Pagination,
    Table,
    Sort,
    DropDownActions,
    // useConfirmDialog,
    // provideConfirmDialog,
};