name: "Vue 3 Component Package"

on: [ pull_request ]

jobs:
  check-js-files:
    name: "Analyze *.js and *.vue files"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Check package-lock.json version
        run: |
          if grep -c '"lockfileVersion": 1,' package-lock.json ; then
            echo "lockfileVersion is 1, please make sure that you are using proper node and npm version"
            exit 1
          fi
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install pnpm
        run: |
          pnpm install          

      - name: Analyze latest files
        run: pnpm run eslint