name: Publish to pnpm

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Bump version and tag
        id: bump_version
        run: |
          VERSION=$(npm version patch -m "chore(release): %s")
          echo "::set-output name=VERSION::$VERSION"

      - name: Push new tag to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:master --tags

      - name: Publish to pnpm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm adduser
          npm whoami
          npm publish
